config/routes.rb
Rails.application.routes.draw do


  



 
  resources :reviews
  resources :rooms
  resources :photos

  root 'pages#home'


  devise_for :users,
             :path => '',
             :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
             :controllers => { :registrations => "registrations" } 
 resources :users, only: [:show]
 resources :rooms do
 	resources :reservations, only: [:create]
 end

 resources :conversations, only: [:index, :create] do
 	resources :messages, only: [:index, :create]
 end

 resources :rooms do
 	 resources :reviews, except: [:show, :index]
  end
get '/preload' => 'reservations#preload'
get '/preview' => 'reservations#preview' 
get '/your_trips' => 'reservations#your_trips' 
get '/your_reservations' => 'reservations#your_reservations' 
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :reservations
  has_many :reviews

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  

  

 
  validates :home_type, presence: true
 validates :room_type, presence: true
 validates :accommodate, presence: true
 validates :bed_room, presence: true
 validates :bath_room, presence: true
 validates :listing_name, presence: true, length: {maximum: 50}

validates :summary, presence: true,  length: {maximum: 500}
validates :address, presence: true

end

app/controllers/rooms_controller.rb
 class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [ :show]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = current_user.rooms
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @photos = @room.photos
    @reviews = Review.where(room_id: @room.id).order("created_at DESC")

    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end

   
  end

  # GET /rooms/new
  def new
    @room = current_user.rooms.build
  end

  # GET /rooms/1/edit
  def edit
    if current_user.id == @room.user.id
    @photos =@room.photos
  else
    redirect_to root_path, notice: "You don't have permission"
    end
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = current_user.rooms.build(room_params)

    respond_to do |format|
      if @room.save

        if params[:images]
          params[:images].each do |image|
           @room.photos.create(image: image)
           end
           end 
           @photos = @room.photos
        format.html { redirect_to edit_room_path(@room), notice: 'Room was successfully created.' }
      
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
         if params[:images]
          params[:images].each do |image|
           @room.photos.create(image: image)
           end
           end 
         


        format.html { redirect_to edit_room_path(@room), notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy

    @photo.destroy
    @photos = Photo.where(room_id: room_id)
    @photos =@room.photos
    respond_to :js

    @room.destroy
  
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:home_type, :room_type, :accommodate, :bed_room, :bath_room, :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_air, :is_heating, :is_internet, :price, :active, :image)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for @room, html: {multipart: true} do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="panel panel-default">
    <div class="panel-heading">
      Create Your Beautiful Place
    </div>
    <div class="panel-body">
      <div class="container">
        
        <div class="row">
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Home Type</label>
              <%= f.select :home_type, [["Apartment", "Apartment"], ["House", "House"]],id: "home_type", prompt: "select....", class: "form-control" %>
            </div>
          </div>
            <div class="col-md-4 select">
            <div class="form-group">
              <label>Room Type</label>
              <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"]], prompt: "select....", class: "form-control" %>
            </div>
          </div>
            <div class="col-md-4 select">
            <div class="form-group">
              <label>Accommodate</label>
              <%= f.select :accommodate, [["1","1"], ["2", "2"]], prompt: "select....", class: "form-control" %>
            </div>
          </div>




        </div>

        <div class="row">
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bedroom</label>
              <%= f.select :bed_room, [["1",1], ["2", 2]], prompt: "select....", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bathroom</label>
              <%= f.select :bath_room, [["1",1], ["2", 2]], prompt: "select....", class: "form-control" %>
            </div>
          </div>

         </div>
        <div class="row">
          <div class="form-group">
            <label>Listing name</label>
            <%= f.text_field :listing_name, placeholder: "Be clear and Descriptive", class: "form-control" %>
          </div>
        </div>

          <div class="row">
          <div class="form-group">
            <label>Summary</label>
            <%= f.text_field :summary, rows: 5, placeholder: "Tell about your house", class: "form-control" %>
          </div>
        </div>

         <div class="row">
          <div class="form-group">
            <label>Address</label>
            <%= f.text_field :address, placeholder: "what is your address", class: "form-control" %>
          </div>
        </div>
        
        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <%= f.check_box :is_tv %> TV
            </div>
            <div class="form-group">
              <%= f.check_box :is_kitchen %> Kitchen
            </div>
            <div class="form-group">
              <%= f.check_box :is_internet%> Internet
            </div>
          </div>

          <div class="col-md-4">
            <div class="form-group">
              <%= f.check_box :is_heating %> Heating
            </div>
            <div class="form-group">
              <%= f.check_box :is_air %> Air conditioning
            </div>
            
          </div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <label>Nightly Price</label>
              <div class="input-group">
              <div class="input-group-addon"> $</div>
              <%= f.text_field :price, placeholder: "eg. $100", class:"form-control" %> 
                
              </div>

            </div>
          </div>
        </div>

        <div class="row">

          <div class="col-md-4">
          <div class="form-group">
          <span class="btn btn-default btn-file">
          <i class="fa fa-cloud-upload fa-lg"></i>Upload Photos

            
               
                <%= file_field_tag "images[]",type: :file, multiple: true %>
                </span>
              
               </div>
              
            </div>
          </div>
       
          <div id="photos"> <%= render 'photos/list' %></div>

        
        <div class="row">
          <div class="form-group">
            <%= f.check_box :active %> Active
          </div>
        </div>


        <div class="actions">
          <%= f.submit "Save", class: "btn btn-primary" %>
        </div>



      </div>
    </div>
  </div>

 
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>


<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul ss="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listing", rooms_path, class: "sidebar-link active" %></li>
       <li class="sidebar-item"><%= link_to "Your Reservation", your_reservations_path, class: "sidebar-link " %></li>
        <li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link " %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Listings
      </div>
      <div class="panel-body">
        <% @rooms.each do |room| %>
        <div class="row">
          <div class="col-md-2">
            <%= image_tag room.photos[0].image.url(:thumb) if room.photos.length > 0 %>
          </div>
          <div class="col-md-7">
            <h4><%= room.listing_name %></h4>
          </div>
          <div class="col-md-3 right">
          <%= link_to "Update", edit_room_path(room), class: "btn btn-primary" %>
          
        </div>
      </div>
      <hr>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
 <div class="panel panel-default">
 <div class="panel-body">
   
   <!--Image -->
   <div class="row">
     <div class="col-md-12">
       <%= image_tag @photos[0].image.url(), class: "img-responsive" if @photos.length > 0 %>
     </div>
   </div>

   <br>

   <!-- Main info -->
   <div class="row">
     <div class="col-md-8">
       <div class="row">
         <div class="col-md-3 text-centre">
           <%= image_tag avatar_url(@room.user), class: "img-circle avatar-large" %><br><br>
           <%= @room.user.fullname %>
         </div>

         <div class="col-md-9">
           <h4><%= @room.listing_name %></h4>
           <%= @room.address %>
           <div class="row text-center row-space-1">
             <div class="col-sm-3">
               <i class="fa fa-home fa-2x"></i>

             </div>
             <div class="col-sm-3">
               <i class="fa fa-users fa-2x"></i>
               </div>
                <div class="col-sm-3">
               <i class="fa fa-bed fa-2x"></i>
               </div>
                <div class="col-sm-3">
               <i class="fa fa-ship fa-2x"></i>
               </div>
              

           </div>

           <div class="row text-centre">
             <div class="col-sm-3">
               <%= @room.home_type %>
             </div>
             <div class="col-sm-3">
               <%= @room.accommodate %> <%= @room.accommodate > 1? "Guests" : "Guest" %>
             </div>
               <div class="col-sm-3">
               <%= @room.bed_room%> <%= @room.bed_room > 1? "Bedrooms" : "Bedroom" %>
             </div>
               <div class="col-sm-3">
               <%= @room.bath_room %> <%= @room.bath_room > 1? "Bathrooms" : "Bathroom" %>
             </div>
           </div>


         </div>
       </div>
     </div>
     <!-- Reservation -->
     <div class="col-md-4">
       <%= render 'reservations/form'  %>
     </div>
   </div>


   <!--About -->
   <div class="row">
     <div class="col-md-12">
       <h2>About This Listing</h2>
       <p><%= @room.summary %></p>
     </div>
   </div>

   <!-- amintities-->
   <div class="row">
     <div class="col-md-2">
       <p>Amentities</p>
     </div>
     <div class="col-md-10">
       <div class="row">
         <div class="col-md-6">
           <ul class="amenities">
             <li class="<%= 'text-line-through' if !@room.is_tv %>">TV</li>
              <li class="<%= 'text-line-through' if !@room.is_kitchen %>">Kitchen</li>
               <li class="<%= 'text-line-through' if !@room.is_internet %>">Internet</li>
           </ul>
         </div>
         <div class="col-md-6">
            <li class="<%= 'text-line-through' if !@room.is_heating %>">Heating</li>
             <li class="<%= 'text-line-through' if !@room.is_air %>">Air Conditioning</li>
         </div>
       </div>
     </div>
   </div>

   <!-- carousal-->
   <div class="row">
     <div class="col-md-10 col-md-offset-1">
       
       <div id="myCarousel" class="carousel slide" data-ride="carousel">

       <% if @photos %>
       <!-- Indicators -->
        <ol class="carousel-indicators">
          <% @photos.each do |photo| %>
          <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
          <% end %>
         </ol>
         <% end %>

           <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
           <% if @photos %>
             <% @photos.each do |photo| %>
    <div class="item <%= 'active' if photo.id == @photos[0].id %>">
       <%= image_tag photo.image.url() %>
       </div>
       <% end %>
       <% end %>
       </div>

    

                <!-- Left and right controls -->
              <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                   <span class="sr-only">Previous</span>
               </a>
              <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
                </a>
                </div>
              </div>
    </div>
    <br>
    <br>
    <hr>
    <!-- Reviews -->
    <div class="row">
      <div class="col-md-12">
      <h3>Reviews <%= @avg_review %> (<%= @reviews.count %></h3>
      <div class="star-rating" data-score= <%= @avg_review %>></div>
      <em> <%= "#{@reviews.length} reviews" %>  </em>
      <div>
        <span class="pull-right">
          <%= link_to "Write a Review", new_room_review_path(@room) %>
        </span>
      </div> 
        <div class="container">
        
       <div class="col-md-7 col-md-offset-1">
       <% if @reviews.blank? %>
        <h3>No review Just Yet, would you like to add the first</h3> 
        <%= link_to "write Review", new_room_review_path(@room), class: "btn btn-danger" %>
         <% else %>
         <% @reviews.order("id desc").each do |review| %>

         <hr>
         <div class="row">
           <div class="col-md-1">
             <%= image_tag avatar_url(review.user), class: "img-circle avatar-medium" %>
           </div>
           <div class="col-md-12">
             <div class="user name">
               <strong><%= review.user.fullname %><div class="star-rating" data-score= <%=
           review.rating %>></div> </strong>
           <span class="pull-right">
           <%= link_to "Remove My Review", [@room, review], method: :delete, data: {confirm: "Are you sure" } %></span>
             </div>
             <div><%= review.created_at.strftime("%v") %></div>
           <p><%=review.comment %></p>
           </div>
         </div>
          
         </div>
          <%  end %>
         <%end %> 
         </div>
         </div>
      </div>
    </div>
   <!-- google maps -->
   <div class="row">
     <div class="col-md-12">

     <div id="map">
       
     </div>
     <style>
      #map {
        margin-top: 60px;
        width: 100%;
        height: 400px;
      }
    </style>

    <script>
        var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 28.4594965, lng: 77.0266383},
          zoom: 8,
           mapType: google.maps.MapTypeId.ROADMAP
        });

      var marker = new google.maps.Marker({
        position: {lat:  28.4594965, lng: 77.0266383},
        title: "AirAlien"
      });
      marker.setMap(map);
      }
    google.maps.event.addDomListener(window, 'load', initMap);
   
    </script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false&callback=initMap"></script>

    <h3>Near by</h3>
    <div class="row">
     <% for room in @room.nearbys(10) %>
     <div class="col-md-4">
       <div class="panel-panel-default">
         <div class="panel-heading">
           <%= image_tag room.photos[0].image.url(:thumb) %>
         </div>
         <div class="panel-body">
           <%= link_to room.listing_name, room %><br>
           (<%= room.distance.round(2) %> miles away)
         </div>
       </div>
     </div>
     <% end %>
    </div>
    

     
  
   
       
     </div>
   </div>


 </div>
   
 </div>




<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>


<script>
$('.star-rating').raty({
  path: '/assets',
  readOnly: true,
  score: function() {
    return $(this).attr('data-score');
  }
});
</script>